resources:
  - name: vijay_pipe
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/utilityfunction           
      
pipelines:
  - name: vijay_utilityfuction
    steps:
      - name: utilityFunctionadding
        type: Bash
        configuration:
#           nodePool: u18-static
          integrations:
            - name: vijay
          inputResources:
            - name: vijay_pipe
            
        execution:
          onExecute: 
            - pushd $res_vijay_pipe_resourcePath    
            - ls -la
            - pwd
            - npm build
            - node node.js
            - cat newBuildPlaneImages.json
            - popd


