resources:
  - name: vijay_pipe
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/utilityfunction           
      
pipelines:
  - name: vijay_utilityfuction
    steps:
      - name: utilityFunctionadding
        type: Bash
        configuration:
#           nodePool: u18-static
          integrations:
            - name: vijay
          inputResources:
            - name: vijay_pipe
            
        execution:
          onExecute: 
#             - bump_semver v3.0.0 major
#             - bump_semver v3.0.0 minor
#             - bump_semver v3.0.0 patch
#             - bump_semver v3.0.0 beta
            - pushd $res_vijay_pipe_resourcePath    
#             - touch keys
            - echo "name =$res_vijay_pipe_gitProvider_name" >> keys
            - replace_envs $PWD/keys 
            - cat keys
            - touch file.txt
            - echo "Hello frog" >> file.txt
            - touch test.txt
            - echo "Hello pipelines team" >> test.txt
            - add_pipeline_files $PWD/file.txt jfrog_pipeline
            - add_pipeline_files $PWD/test.txt jfrog_pipeline
            - node node.js
            - popd


